### ISSUE TITLE
Integrate Icon Generation Task with the "Build" Lifecycle

### ISSUE THREAD

**Issue by qamarelsafadi** [qamarelsafadi/KMPAppIconGeneratorPlugin#4]
## Description

The icon generation task currently needs to be run manually. 

This feature would involve hooking the task into the Gradle build lifecycle, allowing it to be executed automatically when running the standard build tasks. This improvement will streamline the developer experience by removing the need for manual execution.

**Comment by mr3y-the-programmer** [comment]
Hi @qamarelsafadi I've implemented this feature and tested it locally, I've opened a PR for you to review #8. 
I hope it helps.
